package:
  name: geometry
  version: "0.2.4"

build:
  number: 0

source:
  path: ./

requirements:
  build:
    - python  {{python}}
    - setuptools
  host:
    - python
    - numpy
    - pandas
  run:
    - python
    - numpy
    - pandas
test:
  imports:
    - geometry